# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_simulator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15stock_simulator.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\tStockList\x12\x16\n\x06stocks\x18\x01 \x03(\x0b\x32\x06.Stock\"%\n\x05Stock\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1e\n\x0cStockRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"Z\n\nStockPrice\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"Y\n\x0cTradeRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\x12\x18\n\x04type\x18\x03 \x01(\x0e\x32\n.TradeType\x12\r\n\x05price\x18\x04 \x01(\x02\"\x9d\x01\n\rTradeResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\x12\x18\n\x04type\x18\x03 \x01(\x0e\x32\n.TradeType\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x12\n\ntotal_cost\x18\x05 \x01(\x02\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\".\n\x0bPageRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"1\n\x10TradeRequestList\x12\x1d\n\x06trades\x18\x01 \x03(\x0b\x32\r.TradeRequest\"3\n\x11TradeResponseList\x12\x1e\n\x06trades\x18\x01 \x03(\x0b\x32\x0e.TradeResponse*\x1e\n\tTradeType\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\x32\x96\x02\n\x0eStockSimulator\x12\x32\n\nListStocks\x12\x16.google.protobuf.Empty\x1a\n.StockList\"\x00\x12-\n\rGetStockPrice\x12\r.StockRequest\x1a\x0b.StockPrice\"\x00\x12/\n\x0c\x45xecuteTrade\x12\r.TradeRequest\x1a\x0e.TradeResponse\"\x00\x12\x36\n\x11LastTradeRequests\x12\x0c.PageRequest\x1a\x11.TradeRequestList\"\x00\x12\x38\n\x12LastExecutedTrades\x12\x0c.PageRequest\x1a\x12.TradeResponseList\"\x00\x42\x15\xaa\x02\x12\x45xcelMinder.Sharedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_simulator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022ExcelMinder.Shared'
  _TRADETYPE._serialized_start=690
  _TRADETYPE._serialized_end=720
  _STOCKLIST._serialized_start=87
  _STOCKLIST._serialized_end=122
  _STOCK._serialized_start=124
  _STOCK._serialized_end=161
  _STOCKREQUEST._serialized_start=163
  _STOCKREQUEST._serialized_end=193
  _STOCKPRICE._serialized_start=195
  _STOCKPRICE._serialized_end=285
  _TRADEREQUEST._serialized_start=287
  _TRADEREQUEST._serialized_end=376
  _TRADERESPONSE._serialized_start=379
  _TRADERESPONSE._serialized_end=536
  _PAGEREQUEST._serialized_start=538
  _PAGEREQUEST._serialized_end=584
  _TRADEREQUESTLIST._serialized_start=586
  _TRADEREQUESTLIST._serialized_end=635
  _TRADERESPONSELIST._serialized_start=637
  _TRADERESPONSELIST._serialized_end=688
  _STOCKSIMULATOR._serialized_start=723
  _STOCKSIMULATOR._serialized_end=1001
# @@protoc_insertion_point(module_scope)
